from accounts.models import User
from pool.models import Group, GroupMember
u1=User.objects.create_user(username='john', email='a@bc.com', phone_number='+1234567890', address='xy', password='Abcd123$')
u1.save()
u2=User.objects.create_user(username='john2', email='x@bc.com', phone_number='+1234567891', address='xyz', password='Abcd123$')
u2.save()
u3=User.objects.create_user(username='john3', email='y@bc.com', phone_number='+1234567893', address='xyw', password='Abcd123$')
u3.save()
g1=Group(admin=u1, name='g1', description='d')
g1.save()
g2=Group(admin=u2, name='g2', description='d2')
g2.save()
gm1= GroupMember(group=g1, user=u1)
gm1.save()
gm2= GroupMember(group=g2, user=u2)
gm2.save()
gm3 = GroupMember(group=g1, user=u3)
gm3.save()
gm4= GroupMember(group=g2, user=u3)
gm4.save()